<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQdvdGNB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQdvdGNB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQdvdGNB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQdvdGNB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQdvdGNB\App_KernelDevDebugContainer([
    'container.build_hash' => 'QdvdGNB',
    'container.build_id' => '791265ef',
    'container.build_time' => 1583001411,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQdvdGNB');
