<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTGOnNiB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTGOnNiB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTGOnNiB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTGOnNiB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTGOnNiB\App_KernelDevDebugContainer([
    'container.build_hash' => 'TGOnNiB',
    'container.build_id' => '2851cad6',
    'container.build_time' => 1583107701,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTGOnNiB');
